wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.5.6
    t:
      1:
      - 1
      4: 3.5.6
      5: 0.11.2
      8:
      - 3
      - 5
algo_name:
  desc: null
  value: TD3
batch_size:
  desc: null
  value: 256
discount:
  desc: null
  value: 0.99
env:
  desc: null
  value: InvertedPendulumBulletEnv-v0
eval_freq:
  desc: null
  value: 5000
expl_noise:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.0003
max_timesteps:
  desc: null
  value: 1000000
n_random_timesteps:
  desc: null
  value: 10000
noise_clip:
  desc: null
  value: 0.5
policy_freq:
  desc: null
  value: 2
policy_noise:
  desc: null
  value: 0.2
save_model:
  desc: null
  value: false
seed:
  desc: null
  value: 1636989863
tau:
  desc: null
  value: 0.005
